import type { Metadata } from "next";
import { merriweather } from "@/app/ui/fonts";
import "./globals.css";
import Header from "./ui/header/header";
import Footer from "./ui/footer/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header/>
      <body
        className={`${merriweather.className} antialiased bg-primary-beige`}
      >
        {children}
      </body>
      <Footer/>
    </html>
  );
}
